# Generated by Django 4.1.7 on 2023-04-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customuser_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prise_with_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
