# Generated by Django 4.1.7 on 2023-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_game_prise_with_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('is_on_sale', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('prise_with_discount', models.IntegerField(blank=True, null=True)),
                ('haract', models.TextField(blank=True, null=True)),
                ('M3_Lee_garant', models.IntegerField(default=12)),
                ('storage_status', models.BooleanField()),
                ('type10MBT', models.TextField()),
                ('min_range', models.IntegerField()),
                ('max_range', models.IntegerField()),
                ('Sampling_method', models.TextField()),
                ('Measured_gases', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('is_on_sale', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('prise_with_discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
