# Generated by Django 4.1.7 on 2023-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_services_delete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Measured_gases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Sampling_method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
